# fly.toml app configuration file generated for starseed-oracle-temple
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'starseed-oracle-temple'
primary_region = 'sjc'

[build]
  dockerfile = "Dockerfile"
  [build.args]
    NEXT_PUBLIC_SUPABASE_URL = "https://lxzaerwvbkkgbgvyhltq.supabase.co"
    NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4emFlcnd2YmtrZ2JndnlobHRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAyMjIzNzEsImV4cCI6MjA3NTc5ODM3MX0.iIu2QON2_6spLdBx85dZmljnocCF93syogcG5X-GQxQ"
    NEXT_PUBLIC_APP_NAME = "Starseed Oracle Temple"
    NEXT_PUBLIC_APP_URL = "https://thestarseedoracle.com"
    NEXT_PUBLIC_POCKET_PORTAL_BACKEND_URL = "https://api.pocketportal.app"
    POCKET_PORTAL_BACKEND_URL = "https://api.pocketportal.app"
    NEXT_PUBLIC_POSTHOG_KEY = "phc_7cDCkSgfN9hZmMhNHvqQ7cHSuBb5Y7mBqTjEKHyoT72"

[env]
  PORT = "3000"
  NODE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1024mb'
  cpu_kind = 'shared'
  cpus = 4

[deploy]
  strategy = "rolling"